# Generated by Django 3.0.4 on 2020-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
